kurvey/urls.py
from django.urls import path
from kurvey import views

app_name = 'survey'


urlpatterns = [  
    path('questions/<int:question_set_pk>/', views.QuestionListView.as_view(), name='question_list'),
    path('capture/add/<int:question_set_pk>/', views.CaptureManageView.as_view(), name='capture_add'),
    path('capture/edit/<int:question_set_pk>/<int:pk>/', views.CaptureManageView.as_view(), name='capture_edit'),
    path('capture/detail/<int:pk>/', views.CaptureDetailView.as_view(), name='capture_detail'),
    path('capture/auth/<int:question_set_pk>/', views.CaptureAuthView.as_view(), name='capture_auth'),
    path('capture/start/<int:question_set_pk>/', views.CaptureStartView.as_view(), name='capture_start'),

    path('capture/list/<int:qs_pk>/', views.CaptureListView.as_view(), name='capture_list'),
    path('capture/list/', views.CaptureListView.as_view(), name='capture_list'),
]

kurvey/templates/kurvey/base.html
{% load sekizai_tags %}

<html>
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>
        {% render_block "css" %}
    </head>
    <body>
        {% block page_header %} {% endblock %}
        {% block content %} {% endblock %}
        {% block side_content %} {% endblock %}

        {% render_block "js" %}
    </body>
</html>

kurvey/templates/kurvey/base_pdf.html
<html>
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        {% block content %} {% endblock %}
        {% block side_content %} {% endblock %}
        {% block extra_body %}{% endblock %}
    </body>
</html>

kurvey/templates/kurvey/capture_auth.html
{% extends "kurvey/base.html" %}

{% block title %}{{ question_set }} - Capture Authorize{% endblock %}

{% block page_header %}
    <h3>Capture Authorize</h3>
{% endblock %}

<div class="card-header">
    {{question_set}}
</div>

{% block content %}
    <form action="{{ request.get_full_path }}" method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                {% include "kurvey/includes/capture_form.html" %}
            </div>
            <div class="card-footer">
                <button name="_submit" class="btn btn-success">Proceed</button>
            </div>
        </div>
    </form>
{% endblock %}


{% block side_content %}
    <div class="kurvey manage">
    <div class="sidebar">
        <div class="card">
            <div class="card-body p-4">
                <p>Please fill this introductory form to begin answering questions for <b>{{ question_set }}</b></p>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

kurvey/templates/kurvey/capture_detail.html
{% extends "kurvey/base.html" %}
{% load static sekizai_tags display_fields %}

{% block title %}{{ object.question_set }} - Capture Detail{% endblock %}

{% block breadcrumbs %}
    <div id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <div class="text-white0">
            <ol>
            {% if request.user.is_staff %}
                <li><a href='{% url "kurvey:capture_list" %}' class="text-white0">List</a></li>
            {% endif %}
            </ol>
            <h2>{{ object }}</h2>
        </div>
    </div>
    </div>
{% endblock %}

{% block page_header %}
    <h3>Capture Detail</h3>
{% endblock %}

{% block content %}
    <div class="kurvey detail">

        <div class="content">

            <div class="card">
                <div class="card-header">{{ object.question_set }}</div>
                <ul class="list-group list-group-flush">
                    {% for detail in detail_object|get_display_fields:detail_fields %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-3 col-lg-3 col-xs-3">
                                    {{ detail.label|capfirst }}
                                </div>
                                <div class="col-md-9 col-lg-9 col-xs-9">
                                    {{ detail.value }}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <br/>

        <div class="answers">
            <h4>Answers</h4>
            {% include "kurvey/includes/capture_review.html" with capture=object %}
            <div class="clearfix"></div>
        </div>
    </div>

{% endblock %}


{% block side_content %}
    <div class="kurvey detail">
        <div class="sidebar">
            {% if object.date_completed %}
                {% if is_owner or user.is_staff %}
                    <div class="card border-success">
                        <div class="card-header">Completed</div>
                        <div class="card-body">
                            <p>Your have successfully completed the questionnaire.
                                You cannot make anymore changes to the form.</p>
                            <p>You can however print it as a PDF document.</p>

                        </div>
                        <div class="card-footer">
                            <a href='{% url "survey:capture_detail" object.pk %}?action=print'
                               class="btn btn-primary btn-sm rounded-0">
                                <i class="bi bi-printer"></i> Print
                            </a>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                {% if is_owner %}
                    <div class="card border-warning">
                        <div class="card-header">Saved</div>
                        <div class="card-body">
                            <p>Your data has been saved successfully. Click on the complete button below to finalize the
                                process.
                            </p>
                            <p>You can also edit the form again if you wish to change anything.</p>
                        </div>
                        <div class="card-footer">
                            <div class="btn-group">
                                <a href='{{ capture.get_manage_url }}'
                                   class="btn btn-outline-secondary btn-sm rounded-0">
                                    <i class="fa fa-pencil-square-o"></i> Edit
                                </a>
                                <a href='#' id="id_capture_complete" class="btn btn-success btn-sm rounded-0 ">
                                    <i class="fa fa-check-square"></i> Complete
                                </a>
                            </div>

                            <a href='{% url "survey:capture_detail" object.pk %}?action=print'
                               class="btn btn-primary btn-sm rounded-0 float-end">
                                <i class="bi bi-printer"></i> Print
                            </a>

                        </div>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>

    {% addtoblock 'js' %}
        <script type="text/javascript" src='{% static "kurvey/plugins/bootbox/bootbox.min.js" %}'></script>

        <script type="text/javascript">
            $(document).ready(function () {

                $("#id_capture_complete").click(function(e) {
                    bootbox.confirm({
                        message: "Are you sure you want to complete this questionnaire. You will not be able to make anymore changes?",
                        buttons: {
                            confirm: {
                                label: 'Yes',
                                className: 'btn-success'
                            },
                            cancel: {
                                label: 'No',
                                className: 'btn-danger'
                            }
                        },
                        callback: function (result) {
                            if (result){
                                url = '{% url "survey:capture_detail" object.pk %}?action=complete';
                            window.location = url;
                        }
                    }
                });
            });

        });
        </script>
    {% endaddtoblock %}
{% endblock %}

kurvey/templates/kurvey/capture_list.html
{% extends "kurvey/base.html" %}
{% load static sekizai_tags display_fields %}

{% block title %}Capture List{% endblock %}

{% block page_header %}
    <h3>Capture List</h3>
{% endblock %}


{% block content %}
    <div class="kurvey capture-list content">
        <div class="card shadow-sm border-light- rounded-0">
            {% comment %}
                <div class="card-header">

                    <div class="d-flex">
                        <div class="mr-auto">
                            Submitted Data
                        </div>
                        <div class="d-flex align-items-center">

                        </div>
                    </div>
                </div>
            {% endcomment %}
            <div class="card-body p-3 pb-0">
                <table class="table table-sm mb-0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Code</th>
                        <th>User</th>
                        <th>Date created</th>
                        <th>Date completed</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for x in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{{ x.get_absolute_url }}">{{ x.code }}</a></td>
                            <td>{{ x.user }}</td>
                            <td>{{ x.date_created }}</td>
                            <td>{{ x.date_completed }}</td>
                            <td>
                                {% comment %}
                                <a href='{{ x.get_absolute_url }}' type="button"
                                   class="btn btn-secondary btn-sm mb-2 py-0">Details</a>
                                {% endcomment %}
                                <a href='{{ x.get_pdf_url }}' type="button"
                                   class="btn btn-outline-secondary btn-sm mb-1 py-0 rounded-0">Print</a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6">
                                <div class="py-3 small">No results found</div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}


{% block side_content %}
    <div class="kurvey capture-list sidebar">
        {% comment %}
            <div class="card mb-3">
                <div class="card-header">Question Sets</div>
                <div class="card-body p-0">

                    <ul class="list-group">
                        {% for x in question_sets %}
                            <li class="list-group-item rounded-0 {% if x.selected %}active{% endif %}">
                                <a href='{% url "kurvey:capture_list" x.pk %}'>{{ x.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endcomment %}

        <div class="card mb-3">
            <div class="card-header">Filters</div>
            <div class="card-body">
                <form action="" method="get">
                    {{ filter_form }}
                    <div class="clearfix"></div>
                    <input type="submit" value="Filter" class="btn btn-sm btn-dark rounded-0 mt-3 float-end"/>
                </form>

            </div>
        </div>

    </div>
{% endblock %}

kurvey/templates/kurvey/capture_manage.html
{% extends "kurvey/base.html" %}
{% load static %}

{% block title %}{{ question_set.name }} - Capture Manage{% endblock %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}


{% block content %}
<div class="kurvey manage">
    <div class="content">
        <h3>{{ question_set.name }}</h3>

        <form action="{{ request.get_full_path }}" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <div class="card">
                <div class="card-header">
                    {{ form.info.name }}
                </div>
                <div class="card-body">
                    {% include "kurvey/includes/capture_form.html" %}
                </div>
                <div class="card-footer">
                    {% include "kurvey/includes/capture_buttons.html" %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block side_content %}
    <div class="kurvey manage">
    <div class="sidebar mb-3">
        <div class="card">
            <div class="card-header">
                <p class="card-text">Select a section to answer the questions</p>
            </div>
            <ul class="list-group list-group-flush">
                {% for x in group_info.all %}
                    <li class="list-group-item {% if x.pk == group_info.current.pk %}active{% endif %}">
                        <a href='{{ capture.get_manage_url }}?group={{ x.pk }}'>
                            {{ x.get_text }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% if capture and capture.date_validated %}
        <div class="">
            <a href='{{ capture.get_absolute_url }}' class="btn btn-outline-secondary btn-sm mt-3">
                View Details
            </a>
        </div>
        {% endif %}
    </div>
    </div>
{% endblock %}

kurvey/templates/kurvey/capture_manage_popup.html
{% extends "bs4_classic/base_popup.html" %}
{% load media_tags static sekizai_tags %}

{% block all_body %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Question</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Pictures</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active m-2" id="home" role="tabpanel" aria-labelledby="home-tab">
            {% block right_actual_content %}{% endblock %}
        </div>
        <div class="tab-pane m-2" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            {% for capture_answer in capture_answers %}
                <h6>Pictures ({{ capture_answer.capturepicture_set.count }})</h6>

                {% for obj in capture_answer.capturepicture_set.all %}
                    <a data-fancybox="gallery-{{ capture_answer.pk }}" href="{{ obj.picture.gen_image_url }}" >
                        <img src="{{ obj.picture.gen_image_url }}" style="height: 120px" class="m-2">
                    </a>
                {% endfor %}
            {% endfor %}
        </div>
    </div>

    {% addtoblock "js" %}
        <link rel="stylesheet" href='{% static "bs4_classic/fancyapps/jquery.fancybox.min.css" %}' />
        <script src='{% static "bs4_classic/fancyapps/jquery.fancybox.min.js" %}'></script>
    {% endaddtoblock %}
{% endblock %}

kurvey/templates/kurvey/capture_pdf.html
{% extends "kurvey/base_pdf.html" %}
{% load static display_fields %}

{% block pretitle %} 
    <br />
    <h1>{{ object.question_set }}</h1>
{% endblock %}

{% block content %}

    {% block detail_info %}
    <div class="module full">
    <table> 
        <tbody>
        {% for detail in detail_object|get_display_fields:detail_fields %} 
            <tr>
                <td>{{ detail.label|capfirst }}</td>
                <td>{{ detail.value|striptags|default:'---' }}</td>
            </tr>    
        {% endfor %}
        </tbody>
    </table>
    </div>
    {% endblock %}

    <br /><br />

    {% block values_info %}
    {% for grp in review_values %}
    <div class="module full items">
    <table class="items">
        <caption></caption>
        <thead>
            <tr>
                <th style="width: 100%;">{{ grp.group.get_text|upper }}</th>
            </tr>
        </thead>
        <tbody>
            {% for qv in grp.question_values %}
                <tr>
                    <td>
                        {{ qv.question.number }}: {{ qv.text }}
                        <br>
                        <b>{{ qv.value|default:'---' }}</b>
                    </td>
                </tr>
            {% endfor %}
        </tbody> 
    </table>
    </div>
    <br>
    {% endfor %} 
    {% endblock %}


    {% block pictures_info %}
    {% comment %}
    <h2>Pictures</h2>
    <hr />
    {% for grp in review_values_ %}
        <div class="module full">
        <table>
            <caption></caption>
            <thead>
                <tr>
                    <th style="width: 100%">{{ grp.group.get_text|upper }}</th>
                </tr>
            </thead>
            <tbody>
                {% for qv in grp.question_values %}
                    <tr>
                        <td>
                            {% for img in qv.pictures %}
                                <img src="{{ media_url }}{{ img.picture__image }}"
                                     style="height: 120px; margin: 10px" />
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    <br>
    {% endfor %}
    {% endcomment %}
    {% endblock %}

{% endblock %} 

kurvey/templates/kurvey/question_list.html
{% extends "kurvey/base.html" %}


{% block content %}
<div class="row">
<div class="col-md-12">
    
    <table class="table table-bordered" style="border-collapse:collapse;">
        <thead>
            <tr>
                <th>Code</th>
                <th>Number</th>
                <th>Text</th>
                <th>Toggle</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
                <tr data-toggle="collapse_" data-target=".demo1_">
                    <th>{{ obj.scode }}</th>
                    <th>{{ obj.number }}</th>
                    <th>{{ obj.short_text }}</th>
                    <td>
                        <a href="#" data-toggle="collapse" data-target=".chlidren_{{ obj.pk }}">
                            <i class="fa fa-plus-square"></i>
                        </a>
                    </td>
                </tr>
                {% for child in obj.active.all %}
                    <tr class="collapse chlidren_{{ obj.pk }}">
                        <td>{{ child.scode }}</td>
                        <td>{{ child.number }}</td>
                        <td colspan="2">
                            <span class="pl-3">{{ child.short_text }}</span>
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
 
</div>
</div>
{% endblock %} 